// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDavuVNiAf6EOT1-jnQBzCwHZ2kTIqxM',
    appId: '1:623568696597:web:0557dc5627d4844c42a51c',
    messagingSenderId: '623568696597',
    projectId: 'todo-797f0',
    authDomain: 'todo-797f0.firebaseapp.com',
    storageBucket: 'todo-797f0.firebasestorage.app',
    measurementId: 'G-Z27HEXC1LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwb-jCX1liS3Ms6XjV8YtlVaG2YB7Bzo',
    appId: '1:623568696597:android:394657949190ae4442a51c',
    messagingSenderId: '623568696597',
    projectId: 'todo-797f0',
    storageBucket: 'todo-797f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuGlGNGClkskyw1xDou_B1tqjc94lJ4c',
    appId: '1:623568696597:ios:c7ac80f40c32c1cb42a51c',
    messagingSenderId: '623568696597',
    projectId: 'todo-797f0',
    storageBucket: 'todo-797f0.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuGlGNGClkskyw1xDou_B1tqjc94lJ4c',
    appId: '1:623568696597:ios:c7ac80f40c32c1cb42a51c',
    messagingSenderId: '623568696597',
    projectId: 'todo-797f0',
    storageBucket: 'todo-797f0.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJDavuVNiAf6EOT1-jnQBzCwHZ2kTIqxM',
    appId: '1:623568696597:web:6425e7f80eb572ab42a51c',
    messagingSenderId: '623568696597',
    projectId: 'todo-797f0',
    authDomain: 'todo-797f0.firebaseapp.com',
    storageBucket: 'todo-797f0.firebasestorage.app',
    measurementId: 'G-18KHCME2Z3',
  );
}
